version: "3"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/templates
      - frontend-build:/usr/share/nginx/html
      - photos:/usr/share/nginx/html/photos
    environment:
      - NGINX_PORT=3000
    env_file:
      - .env
    ports:
      - 3000:3000
    links:
      - frontend
      - backend
      - grafana
    depends_on:
      - backend
      - frontend
      - grafana
      
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    env_file:
      - .env
    command: uvicorn --factory app:get_app --port 8000 --host 0.0.0.0
    restart: always
    volumes: 
      - photos:/src/photos
    links:
      - postgres
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    volumes:
      - frontend-build:/src/build
    depends_on:
      - backend

  grafana:
    build: ./grafana
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  pgdata:

  frontend-build:

  photos:
    
  grafana-data:
