version: "3"
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata-dev:

  photos-dev:
